obj-$(CONFIG_RTOS) += src/croutine.c
obj-$(CONFIG_RTOS) += src/event_groups.c
obj-$(CONFIG_RTOS) += src/list.c
obj-$(CONFIG_RTOS) += src/queue.c
obj-$(CONFIG_RTOS) += src/stream_buffer.c
obj-$(CONFIG_RTOS) += src/tasks.c
obj-$(CONFIG_RTOS) += src/timers.c

CONFIG_FLAGS +=
INCLUDE_DIR  += include
INCLUDE_DIR  += config
